name: Python testing package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.6", "3.7", "3.8", "3.9"]
        steps:
            - uses: actions/checkout@v3
            - name: Initial testing ${{ matrix.python-version }}
              uses: actions/setup-pyton@v3
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Lint
              run: |

                  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                  flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics 
            - name: Testing with pytest
              run: |
                  pip install pytest
                  pip install pytest-cov
                  pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
